import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useContext, useEffect, useState } from 'react'
import Navbar from '@/components/Navbar';
import Leftbar from '@/components/Leftbar';
import Main from '@/components/Main';
import Rightbar from '@/components/Rightbar';
import { AuthContext } from '@/context/authContext';
import { Router, useRouter } from 'next/router';
import Link from 'next/link';




export default function Home() {

  const {currentUser} = useContext(AuthContext)
  const router = useRouter();


  useEffect(()=>{
    if(currentUser === null){
      router.push("/login")
   }
  },[])


  return (
    <>
      <Head>
        <title>SocMedia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
 
      <main className=' bg-gray-100 dark:bg-slate-700  mx-auto max-w-[1600px]'  >
       <Navbar/>
       <div className=' flex items-start justify-between pt-1 '>
        <Leftbar/>
        <Main/>
        <Rightbar/>
       </div>
      </main>
      
    </>
  )
}
